yii-fwa/models/Laporan.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "laporan".
 *
 * @property int $id
 * @property int $user_id
 * @property int $unit1_id
 * @property int $unit2_id
 * @property int $lokasi_id
 * @property int $kondisi_id
 * @property string $keterangan
 * @property string $submit_date
 *
 * @property Kondisi $kondisi
 * @property Lokasi $lokasi
 * @property Unit1 $unit1
 * @property Unit2 $unit2
 * @property User $user
 */
class Laporan extends \yii\db\ActiveRecord
{
    
        public $keluarga;
        public $lingkungan;
        public $sakit;
        public $today;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'laporan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'unit1_id', 'unit2_id', 'lokasi_id', 'kondisi_id', 'keterangan', 'submit_date'], 'required'],
            [['user_id', 'unit1_id', 'unit2_id', 'lokasi_id', 'kondisi_id'], 'integer'],
            [['keluarga', 'lingkungan', 'sakit'], 'required'],
            [['keluarga', 'lingkungan', 'sakit'], 'string'],
            [['submit_date','today'], 'safe'],
            [['keterangan'], 'string', 'max' => 255],
            [['kondisi_id'], 'exist', 'skipOnError' => true, 'targetClass' => Kondisi::className(), 'targetAttribute' => ['kondisi_id' => 'id']],
            [['lokasi_id'], 'exist', 'skipOnError' => true, 'targetClass' => Lokasi::className(), 'targetAttribute' => ['lokasi_id' => 'id']],
            [['unit1_id'], 'exist', 'skipOnError' => true, 'targetClass' => Unit1::className(), 'targetAttribute' => ['unit1_id' => 'id']],
            [['unit2_id'], 'exist', 'skipOnError' => true, 'targetClass' => Unit2::className(), 'targetAttribute' => ['unit2_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'unit1_id' => 'Unit1 ID',
            'unit2_id' => 'Unit2 ID',
            'lokasi_id' => 'Lokasi ID',
            'kondisi_id' => 'Kondisi ID',
            'keterangan' => 'Keterangan',
            'submit_date' => 'Submit Date',
            'keluarga' => 'Keluarga',
            'lingkungan' => 'Lingkungan',
            'sakit' => 'Sakit',
            'today' => 'Pilih Tanggal',
        ];
    }

    /**
     * Gets query for [[Kondisi]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKondisi()
    {
        return $this->hasOne(Kondisi::className(), ['id' => 'kondisi_id']);
    }

    /**
     * Gets query for [[Lokasi]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLokasi()
    {
        return $this->hasOne(Lokasi::className(), ['id' => 'lokasi_id']);
    }

    /**
     * Gets query for [[Unit1]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUnit1()
    {
        return $this->hasOne(Unit1::className(), ['id' => 'unit1_id']);
    }

    /**
     * Gets query for [[Unit2]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUnit2()
    {
        return $this->hasOne(Unit2::className(), ['id' => 'unit2_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */

    public function getNik()
    {
        return $this->hasOne(User::className(), ['nik' => 'nik_id']);
    }
}

yii-fwa/controllers/LaporanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Laporan;
use app\models\LaporanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Unit2;
use app\models\Lokasi;
use app\models\Kondisi;
use yii\helpers\ArrayHelper;
use yii\data\ActiveDataProvider;
use app\models\User;


/**
 * LaporanController implements the CRUD actions for Laporan model.
 */
class LaporanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['POST'],
                    'delete' => ['POST'],
                ],
            ],

            // 'access' => [
            //     'class' => AccessControl::className(),
            //     'rules' => [
            //         [
            //             'actions' => ['index', 'rekap'],
            //             'allow' => true,
            //             // 'roles' => ['@'],
            //         ],
            //         [
            //             'actions' => ['checkin','kondisi','lokasi','lingkungan'],
            //             'allow' => true,
            //             // 'roles' => ['@'],
            //         ],

 
            //     ],
            // ]
            
        ];
    }

    /**
     * Lists all Laporan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LaporanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $unit2 = Unit2::find()->all();
        $unit2 = ArrayHelper::map($unit2,'id','unit2');

        $lokasi = Lokasi::find()->all();
        $lokasi = ArrayHelper::map($lokasi,'id','lokasi');

        $kondisi = Kondisi::find()->all();
        $kondisi = ArrayHelper::map($kondisi,'id','kondisi');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'unit2' => $unit2,
            'lokasi' => $lokasi,
            'kondisi' => $kondisi,
        ]);
    }

    /**
     * Displays a single Laporan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Laporan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Laporan();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Laporan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Laporan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCheckin()
    {       
        $user = Yii::$app->user->identity->nik;
        $today = date('Y-m-d');
        $query = Laporan::find()->where(['nik_id' => $user])
                                ->andWhere(['like','submit_date',$today]);
        $model = $query->one();
                                
        $count = $query->count();

        if($count > 0 ){
            return $this->render('checkin',[
                'model' => $model,
            ]);
        } else {
            return $this->redirect(['lokasi']);
        }      
        
    }

    public function actionLokasi()
    {       
        return $this->render('lokasi');
    }

    public function actionChecklokasi($lokasi)
    {       
        return $this->redirect(['kondisi','lokasi'=>$lokasi]);
    }

    public function actionKondisi()
    {       
        return $this->render('kondisi');
    }

    public function actionCheckkondisi($lokasi,$kondisi)
    {       
        return $this->redirect(['lingkungan','lokasi'=>$lokasi,'kondisi'=>$kondisi]);
    }

    public function actionLingkungan()
    {       
        $model = new Laporan();
        $kondisi = Kondisi::find()->all();
        $kondisilist = ArrayHelper::map($kondisi,'id','kondisi');

        if ($model->load(Yii::$app->request->post())) {

            $request = Yii::$app->request;
            $model->lokasi_id = $request->get('lokasi');
            $model->kondisi_id = $request->get('kondisi');

            $model->nik_id = Yii::$app->user->identity->nik;
            $model->unit1_id = Yii::$app->user->identity->unit1_id;
            $model->unit2_id = Yii::$app->user->identity->unit2_id;
           
            $ha = 'Keluarga : '. $model->keluarga;
            $hi = ' // Lingkungan : '. $model->lingkungan;
            $hu = ' // Sakit : '. $model->sakit;

            if($model->sakit == null){
                $hu = '';
            }
            $model->keterangan = $ha. $hi .$hu;

            $model->submit_date = date('Y-m-d H:i:s');

            $model->save(false);

            return $this->redirect(['checkin']);
        }

        return $this->render('lingkungan', [
            'model' => $model,
            'kondisilist' => $kondisilist,
        ]);
        
    }

    public function actionChecklingkungan($id)
    {       
        return $this->redirect(['checkin']);
    }

    public function actionRekap()
    {       
        $model = new Laporan();       

        if ($model->load(Yii::$app->request->post())) {

            $date = $model->today;
            
        }  else {
            $date = date('Y-m-d');
            
        }

        // $query = (new Query())
        //          ->select('u.id,u.nik')
        //          ->from('laporan l')
        //          ->rightJoin('user u', 'l.user_id=u.id')
        //          ->where(['l.user_id'=> null]);
        $subquery = Laporan::find()->select('nik_id')->where(['like','submit_date',$date]);

        $query = Laporan::find()->select(['u.id AS id','u.nik AS nik'])
                        ->from('laporan l')
                        ->rightJoin('user u', ['u.nik'=>$subquery])
                        ->where(['l.nik_id'=> null]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => ['defaultOrder' => ['id' => SORT_ASC]]
        ]);

        
        $searchModel = new LaporanSearch();
        // $dataProvider = $searchModel->search2(Yii::$app->request->queryParams,$query);

        return $this->render('rekap',[
            'model' => $model,
            'date' => $date,
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);   
                                  
    }


    /**
     * Finds the Laporan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Laporan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Laporan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

yii-fwa/views/laporan/checkin.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;



/* @var $this yii\web\View */
/* @var $model app\models\Laporan */

$this->title = 'Check-In';
$this->params['breadcrumbs'][] = ['label' => 'Laporans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="col-lg-6 col-lg-offset-3">
 
    <h3 style="color:red">SEMANGAT PAGI!!!</h3>
    <h4><?= Yii::$app->user->identity->nama .' ('.Yii::$app->user->identity->nik .')' ?></h4>


    <div class="callout callout-info">
      <h4>Anda sudah check-in hari ini</h4>

      <b>Lokasi Bekerja : <?= $model->lokasi->lokasi ?></b></br>
      <b>Kondisi Anda : <?= $model->kondisi->kondisi ?></b></br>
      <b>Waktu Check-in : <?= $model->submit_date ?> </b>
    </div>

    <div class="kondisi">
        
        <?php

           echo Html::img('@web/img/infoconona.jpg',['alt'=>'Info Corona', 'class'=>'img-responsive']);
            
        ?>
        <div class="box-footer">
            <?= Html::a('Rekap Harian', ['rekap'],['class' => 'btn btn-primary btn-block']) ?>
            <?= Html::a('Keluar', ['/site/logout'],['class' => 'btn btn-danger btn-block','data-method' => 'post']) ?>
        </div>
    </div>
</div>

yii-fwa/views/laporan/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\date\DatePicker;


/* @var $this yii\web\View */
/* @var $searchModel app\models\LaporanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Laporan';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="laporan-index " style="margin: 3% 7% 7% 7%">
    <div class="text-center">
        <h2>LAPORAN PRESENSI HUMAN RESOURCE TREG III</h2>
    </div>

    <div class="box box-primary" style="margin-top:30px">
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                
                [
                    'attribute' => 'nik_id',
                    'label' => 'Nama Karyawan',
                    'value' => 'nik.nama',
                    'contentOptions' => ['class' => 'text-left'],
                ], 
                [
                    'class' => 'yii\grid\DataColumn',
                    'attribute' => 'unit2_id',
                    'label' => 'Unit',
                    'value' => 'unit2.unit2',
                    'contentOptions' => ['class' => 'text-left'],
                    'filter' => Html::activeDropDownList($searchModel, 'unit2_id', $unit2,
                    ['class'=>'form-control','prompt' => ''])
                ], 
                [
                    'attribute' => 'lokasi_id',
                    'label' => 'Lokasi Bekerja',
                    'value' => 'lokasi.lokasi',
                    'filter' => Html::activeDropDownList($searchModel, 'lokasi_id', $lokasi,
                    ['class'=>'form-control','prompt' => ''])
                ], 
                [
                    'attribute' => 'kondisi_id',
                    'label' => 'Kondisi',
                    'value' => 'kondisi.kondisi',
                    'filter' => Html::activeDropDownList($searchModel, 'kondisi_id', $kondisi,
                            ['class'=>'form-control','prompt' => ''])
                ],     
            
                'keterangan',
                [
                    'attribute' => 'submit_date',
                    'value' => 'submit_date',
                    'filter' => DatePicker::widget(['model'=>$searchModel,
                                                    'attribute' => 'submit_date',
                                                    'language' => 'id',                                                     
                                                    'pluginOptions' => [
                                                        'autoclose'=>true,
                                                        'format' => 'yyyy-mm-dd',
                                                    ]]),
                    'format' => 'raw',
                ],
                
            ],
        ]); ?>
              
            </div>
            <!-- /.box-body -->
            
          </div>
</div>

yii-fwa/views/laporan/kondisi.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\bootstrap\Alert;

/* @var $this yii\web\View */
/* @var $model app\models\Laporan */

$this->title = 'Lapor Kondisi';

$request = Yii::$app->request;
$lokasi = $request->get('lokasi');

?>

<div class="col-lg-6 col-lg-offset-3">
   
    <h3 style="color:red">SEMANGAT PAGI!!!</h3>
    <h4><?= Yii::$app->user->identity->nama .' ('.Yii::$app->user->identity->nik .')' ?></h4>
        
    <div class="callout callout-warning">

            <h4>Anda belum check-in hari ini</h4>
            <p>Silahkan laporkan kondisi kesehatan Anda dan lokasi bekerja hari ini</p>

    </div>

    <h4 class="text-center">Bagaimana kondisi Anda hari ini?</h4>

    <div class="row " style="padding-top:10px">
        <div class="col-lg-6 col-xs-6">
        <?php
            $sakit = Html::img('@web/kondisi/sakit.png',['alt'=>'sakit','class'=>'img-responsive',]);
            echo Html::a($sakit, ['laporan/checkkondisi','lokasi'=>$lokasi,'kondisi'=>1]);
        ?>
        </div>
        <div class="col-lg-6 col-xs-6">
        <?php
            $kurangfit = Html::img('@web/kondisi/kurangfit.png',['alt'=>'kurangfit','class'=>'img-responsive']);
            echo Html::a($kurangfit, ['laporan/checkkondisi','lokasi'=>$lokasi,'kondisi'=>2]);
        ?>
        </div>
        <div class="col-lg-6 col-lg-offset-3 col-xs-6 col-xs-offset-3">
        <?php         
            $sehat = Html::img('@web/kondisi/sehat.png',['alt'=>'sehat','class'=>'img-responsive']);
            echo Html::a($sehat, ['laporan/checkkondisi','lokasi'=>$lokasi,'kondisi'=>3]);
        ?>
        </div>
    </div>    
</div>

yii-fwa/views/laporan/lingkungan.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $model app\models\Laporan */

$this->title = 'Lapor Lingkungan';

$request = Yii::$app->request;
$lokasi = $request->get('lokasi');
$kondisi = $request->get('kondisi');


?>

<div class="col-lg-6 col-lg-offset-3">
   
    <h3 style="color:red">SEMANGAT PAGI!!!</h3>
    <h4><?= Yii::$app->user->identity->nama .' ('.Yii::$app->user->identity->nik .')' ?></h4>
    <div class="callout callout-warning">

            <h4>Anda belum check-in hari ini</h4>
            <p>Silahkan laporkan kondisi kesehatan Anda dan lokasi bekerja hari ini</p>

    </div>

    <h4 class="text-center">Laporkan kondisi Keluarga dan Lingkungan hari ini</h4>

    <?php $form = ActiveForm::begin([
                    'fieldConfig' => [
                        'template' => "{label} \n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
                        'labelOptions' => ['class' => 'col-lg-3 control-label'],
                    ],
                ]); ?>
        <div class="box-body table-responsive">

        <?php

        if($kondisi == 1){
            echo $form->field($model, 'sakit')->textInput(['placeholder' => 'Penyakit yang sedang diderita Anda'])
                ->label('Sakit');
        } else {
             $model->sakit = null;
        }
        ?>

        <?= $form->field($model,'keluarga')->dropDownList($kondisilist,
             [
                 'prompt'=>'Bagaimana kondisi keluarga?',
             ]); 
        ?> 

        <?= $form->field($model,'lingkungan')->dropDownList($kondisilist,
             [
                 'prompt'=>'Bagaimana kondisi lingkungan?',
             ]); 
        ?> 


        </div>
        <div class="box-footer">
            <?= Html::submitButton('Kirim', ['class' => 'btn btn-success btn-block']) ?>
        </div>
        <?php ActiveForm::end(); ?>

</div>

yii-fwa/views/laporan/lokasi.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Laporan */

$this->title = 'Lapor Loker';

?>

<div class="col-lg-6 col-lg-offset-3">
   
    <h3 style="color:red">SEMANGAT PAGI!!!</h3>
    <h4><?= Yii::$app->user->identity->nama .' ('.Yii::$app->user->identity->nik .')' ?></h4>
    <div class="callout callout-warning">

            <h4>Anda belum check-in hari ini</h4>
            <p>Silahkan laporkan kondisi kesehatan Anda dan lokasi bekerja hari ini</p>

    </div>

    <h4 class="text-center">Dimana Anda bekerja hari ini?</h4>

    <div class="row"  style="padding-top:10px">
        <div class="col-lg-6 col-xs-6">
        <?php
            $wfh = Html::img('@web/lokasi/wfh.png',['alt'=>'WFH','class'=>'img-responsive']);
            echo Html::a($wfh, ['laporan/checklokasi','lokasi'=>1]);
        ?>
        </div>
        <div class="col-lg-6 col-xs-6">
        <?php
            $wfso = Html::img('@web/lokasi/wfso.png',['alt'=>'WFSO','class'=>'img-responsive']);
            echo Html::a($wfso, ['laporan/checklokasi','lokasi'=>2]);
        ?>
        </div>
        <div class="col-lg-6 col-xs-6" style="padding-top:30px">
        <?php         
            $wfo = Html::img('@web/lokasi/wfo.png',['alt'=>'WFO','class'=>'img-responsive']);
            echo Html::a($wfo, ['laporan/checklokasi','lokasi'=>3]);
        ?>
        </div>
        <div class="col-lg-6 col-xs-6" style="padding-top:30px">
        <?php         
            $cuti = Html::img('@web/lokasi/cuti.png',['alt'=>'Cuti','class'=>'img-responsive']);
            echo Html::a($cuti, ['laporan/checklokasi','lokasi'=>4]);
        ?>
        </div>
    </div>
    <div class="box-footer">
        <?= Html::a('Keluar', ['/site/logout'],['class' => 'btn btn-danger btn-block','data-method' => 'post']) ?>
    </div>         
   
</div>